### PR TITLE
Add container image tab to lambda docs

### PR DESCRIPTION
**Pull request by AlexanderWert**
Agent docs depending on this change:
- https://github.com/elastic/apm-agent-java/pull/2658
- https://github.com/elastic/apm-agent-python/pull/1565
- https://github.com/elastic/apm-agent-nodejs/pull/2747

### CODE REVIEW

**Comment by AlexanderWert** [comment]
Need to wait for the next release for the docker image being created to end to end test the docs in this PR.

**Review by bmorelli25 — APPROVED** [review]
LGTM

**Comment by bmorelli25** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.3|[](https://github.com/elastic/apm-aws-lambda/pull/218)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Comment by bmorelli25** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.2|[](https://github.com/elastic/apm-aws-lambda/pull/219)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
