### PR TITLE
Add server configurations back in

### PR DESCRIPTION
**Pull request by estolfo**
I unintentionally removed the server configurations in a previous PR and I'm opening this PR so we can discuss whether we want these settings to be configurable.

Questions:
- [ ] `ReadTimeout` and `WriteTimeout` are set to their zero value (0) if not set otherwise, which means there will be no timeout. Do we want users to be able to set these timeouts?
- [ ] Do we want users to be able to set a different `ReadTimeout` and `WriteTimeout`? Currently, they are set to the same user-configured value.
- [ ] `DefaultMaxHeaderBytes` is what is used for `MaxHeaderBytes` if it's not set otherwise. [Its value is 1 << 20](https://cs.opensource.google/go/go/+/refs/tags/go1.17.3:src/net/http/server.go;l=855), so I don't see the point of hardcoding it ourselves to that value.

I personally think we should provide as few configuration options as possible to the user and only options in later if we need them.

### CODE REVIEW

**Comment by astorm** [comment]
In general I'm right there with you with keeping configuration to a minimum, but here's my general thinking on why we might want the timeouts configurable

1. I'm uneasy with the default timeout of 0 -- I'm concerned about the the server staying open indefinitely and keeping the execution environment unfrozen/live, running up bill time 

2. If a timeout is necessary, allowing users to influence this value also seems necessary.  My thinking is if a user needs to extend this timeout for some unseen reason it doesn't seem reasonable to expect them to wait for us to do a release cycle. 

3. This [isn't the first time we've discussed](https://github.com/elastic/apm-aws-lambda/issues/61) this variable, so per #61 we might also consider using `ELASTIC_APM_API_REQUEST_TIME` "plus a little more" as a value.  This reduces the number of variables a user needs to configure, but also gives them indirect control over the timeout.

**Comment by estolfo** [comment]
Those are good points, I agree we should keep the config in for the timeouts. We can discuss/change the name via the separate issue, which you've referenced.
What about `MaxHeaderBytes`? Should we remove that explicit configuration and rely on the default value, which is what we are using now anyway?

**Review by astorm — COMMENTED** [review]
> What about MaxHeaderBytes? Should we remove that explicit configuration and rely on the default value, which is what we are using now anyway?

Hmm, thinking that one through, making `MaxHeaderBytes` user-configurable seems like too much configuration complication at this point.

Re: whether we need an explicit value or not — that's a "six of one, half dozen the other" decision for me, but talking though those trade-offs

- Having an explicit value of 1MB (all hail bitwise arithmetic: `1 << 20`) means our code is slightly more complicated

- Not having an explicit value means we're relying on a default, which might be different in older versions of Go or change in a future version of go

So in my mind having a default means we're more in control of how our program will behave when/if folks compile it themselves, so I'd be in favor of keeping it.

**Comment by estolfo** [comment]
ok @astorm that works for me 👍🏼

**Review by astorm — APPROVED** [review]
👍

**Pull request merged**
