### PR TITLE
docs: update lambda config

### PR DESCRIPTION
**Pull request by bmorelli25**
### Summary

Updates lambda config options:

* Moves deprecated options to the bottom of the list
* Cleans up deprecation text
* Adds `ELASTIC_APM_LAMBDA_CAPTURE_LOGS`

Closes https://github.com/elastic/apm-aws-lambda/issues/323.

### CODE REVIEW

**Review by kruskall — APPROVED** [review]
LGTM! Thanks for this!

**Comment by bmorelli25** [comment]
## 💚 All backports created successfully

| Status | Branch | Result |
|:------:|:------:|:------|
|✅|8.6|[](https://github.com/elastic/apm-aws-lambda/pull/369)|

### Questions ?
Please refer to the [Backport tool documentation](https://github.com/sqren/backport)

**Pull request merged**
